name:                taipeiOnApi
version:             0.1.0.0
github:              "h-alice/taipeiOnApi"
license:             GPL-3.0-or-later
author:              "h-alice"
maintainer:          "admin@halice.art"
copyright:           "2025 Wayne 'h-alice' Hong"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Library for TaipeiON message API
# category:            Web

description:         Please see the README on GitHub at <https://github.com/h-alice/taipeiOnApi#readme>

dependencies:
- base >= 4.7 && < 5
- text                  # Essential text processing
- bytestring            # Essential bytestring processing
- base64-bytestring     # Base64 encoding 
- aeson                 # JSON handling
- hspec                 # Testing framework
- raw-strings-qq        # Raw string handling
- containers
- http-conduit
- http-types
- http-client

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

#executables:
#  taipeiOnApi-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - taipeiOnApi

tests:
  taipeiOnApi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taipeiOnApi
