name:                taipeion-api
version:             0.1.0.0
github:              "h-alice/taipeion-message-api"
license:             BSD-3-Clause
author:              "Wayne Hong (h-alice) <admin@halice.art>"
maintainer:          "Wayne Hong (h-alice) <admin@halice.art>"
copyright:           "2025 Wayne Hong (h-alice)"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md
- GUIDE.md

tested-with:         
  - GHC == 9.6.7
  - GHC == 9.10.2

synopsis:            Library for TaipeiON message API
category:            Api

description:         Please see the README on GitHub at <https://github.com/h-alice/taipeion-message-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.1.2 && < 2.3
- containers
- bytestring
- text
- base64-bytestring >= 1.2.1 && < 1.3
- hspec >= 2.11.12 && < 2.12
- http-client >= 0.7.19 && < 0.8
- http-types >= 0.12.4 && < 0.13
- http-conduit >= 2.3.9 && < 2.4
- raw-strings-qq >= 1.1 && < 1.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  taipeion-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taipeion-api
